# -*- coding: utf-8 -*-
"""MachineLearning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pRjKIVptcR0tmL7GMRP2n1T5J05ms9Pd
"""

from google.colab import files
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import io

print("Manda o arquivo")
pre = files.upload()
nome_arquivo = list(pre.keys())[0]
db = pd.read_csv(io.BytesIO(pre[nome_arquivo]), delimiter=";", low_memory=False)

print("A base de dados tem %d linhas e %d colunas" % (len(db.index), len(db.columns)))

print("Visualizando as 5 primeiras linhas")
db.head()

print("Visualiza todas as respostas de uma pergunta especifica")
db["Quantas pessoas da sua família moram junto com você?"]

print("Visualiza todas as respostas entre 50 e 75")
db[50:75]

print("Organiza em linhas e colunas as respostas de uma pergunta especifica")
db.loc[0:3, ["Quantas pessoas da sua família moram junto com você?"]]

print("Apresenta as respostas da pergunta em especifico acima de 4")
db[db["Quantas pessoas da sua família moram junto com você?"] > '4']

print("Mostra da pergunta em especifico quais estão NaN (sem resposta)")
db[db["Quantas pessoas da sua família moram junto com você?"].isna()]

print("Mostra quais respostas não foram respondidas logo está NaN")
db[db.isna().any(axis = 1)]

print("Mosta a quantidade de NaN em cada pergunta")
db.isnull().sum()

db2 = db.dropna(axis = 0)

print("Preenche todos os NaN com yes")
db_full = db.fillna(value = "yes")

#Mostra se tem alguma resposta nula NaN
db_full[db_full.isna().any(axis = 1)]

#se colocar (db) irá aparecer a arquivo originarl
#Já o (db_full) mostra o alterado
db_full